"""End-to-end smoke test for the Genblaze runner.

Real mode (B2 + a running Alias, configured via env): synthesizes a short
project, persists every take + manifest to Backblaze B2, prints a per-chunk
provenance report, and verifies the final manifest. This is the proof-of-life
to run the moment B2 creds land.

Offline self-test (``--offline``, or when B2/Alias are not configured):
drives the *real* Genblaze pipelines with a built-in fake client and no sink
(assets stay ``file://``), so the script's wiring is validated without any
cloud creds.

Usage::

    python -m genblaze_runner.smoke                 # auto: real if env set, else offline
    python -m genblaze_runner.smoke --offline       # force the offline self-test
    python -m genblaze_runner.smoke --simulate-reroll   # offline, demo a re-roll
    python -m genblaze_runner.smoke --text "Custom narration."

Real-mode env:
    ALIAS_BASE_URL, ALIAS_INTERNAL_SECRET,
    B2_BUCKET, B2_KEY_ID, B2_APP_KEY, B2_REGION

Exit code: 0 on PASS, 1 on FAIL.
"""

from __future__ import annotations

import argparse
import logging
import os
import sys
import traceback
from dataclasses import dataclass

from genblaze_alias._client import AliasClient, TtsResult
from genblaze_runner.config import RunnerConfig
from genblaze_runner.orchestrator import Orchestrator, ProjectResult
from genblaze_runner.sink import build_sink

# Our providers don't register a Genblaze model "family", so the pipeline emits a
# benign per-step "preflight.unknown ... permissive fallback" warning. Quiet it for
# clean demo output. (Follow-up: register a ModelRegistry to make this authoritative.)
logging.getLogger("genblaze.pipeline").setLevel(logging.ERROR)

DEFAULT_TEXT = (
    "Welcome to the future of media provenance. "
    "Every word here is verifiable. "
    "This audio was generated by Alias and orchestrated by Genblaze."
)


@dataclass
class SmokeOutcome:
    passed: bool
    mode: str
    result: ProjectResult | None
    notes: list[str]


# --------------------------------------------------------------------------
# Offline fake client (exercises the real pipelines without cloud/ffmpeg)
# --------------------------------------------------------------------------


class _OfflineClient:
    _WAV = b"RIFF\x24\x00\x00\x00WAVEfmt " + b"\x00" * 32
    _MP3 = b"ID3\x03\x00\x00\x00\x00\x00\x00" + b"\xff\xfb\x90\x00" + b"\x00" * 64

    def __init__(self, *, simulate_reroll: bool = False) -> None:
        self.simulate_reroll = simulate_reroll
        self._scored = 0

    def chunk(self, text: str, *, chunk_mode: str | None = None) -> list[dict]:
        parts = [p.strip() for p in text.replace("!", ".").replace("?", ".").split(".") if p.strip()]
        if not parts:
            return [{"position": 0, "text": text, "break_after": "sentence"}]
        return [{"position": i, "text": f"{p}.", "break_after": "sentence"} for i, p in enumerate(parts)]

    def generate_chunk(self, voice_id, text, *, settings=None, seed=None) -> TtsResult:
        return TtsResult(audio=self._WAV, content_type="audio/wav")

    def score(self, text, audio, *, filename="chunk.wav") -> dict:
        self._scored += 1
        if self.simulate_reroll and self._scored == 1:
            return {"available": True, "ok": False, "problems": ["TRUNC"], "score": 0.5, "trim_at_ms": None}
        return {"available": True, "ok": True, "problems": [], "score": 0.97, "trim_at_ms": None}

    def stitch(self, chunks, *, output_format, break_after=None) -> TtsResult:
        return TtsResult(audio=self._MP3, content_type="audio/mpeg")

    def trim(self, audio, trim_at_ms, *, filename="chunk.wav") -> TtsResult:
        return TtsResult(audio=self._WAV, content_type="audio/wav")


# --------------------------------------------------------------------------
# Runners
# --------------------------------------------------------------------------


def run_offline(*, text=DEFAULT_TEXT, voice="default", output_format="mp3_44100_128",
                seed=None, max_concurrency=1, simulate_reroll=False) -> SmokeOutcome:
    client = _OfflineClient(simulate_reroll=simulate_reroll)
    orchestrator = Orchestrator(client=client, sink=None, max_rerolls=3)
    result = orchestrator.synthesize_project(
        text=text, voice=voice, output_format=output_format, base_seed=seed, max_concurrency=max_concurrency,
    )
    notes: list[str] = []
    passed = True
    if not result.final.url.startswith("file://"):
        passed, _ = False, notes.append(f"expected a file:// final URL offline, got {result.final.url}")
    if not result.manifest.verify():
        passed, _ = False, notes.append("manifest.verify() returned False")
    return SmokeOutcome(passed=passed, mode="offline", result=result, notes=notes)


def run_real(config: RunnerConfig, *, text=DEFAULT_TEXT, voice="default",
             output_format="mp3_44100_128", seed=None, max_concurrency=1) -> SmokeOutcome:
    client = AliasClient(
        base_url=config.alias_base_url, internal_secret=config.alias_internal_secret,
    )

    # Preflight: confirm Alias is reachable and the internal secret is accepted.
    try:
        client.chunk("Smoke preflight.")
    except Exception as exc:  # noqa: BLE001
        return SmokeOutcome(False, "real", None, [f"Alias /v1/internal preflight failed: {exc}"])

    sink = build_sink(config)
    if sink is None:
        return SmokeOutcome(False, "real", None, ["B2 is not configured (set B2_BUCKET / B2_KEY_ID / B2_APP_KEY)."])

    orchestrator = Orchestrator(
        client=client, sink=sink, output_dir=config.output_dir, max_rerolls=config.max_rerolls,
    )
    result = orchestrator.synthesize_project(
        text=text, voice=voice, output_format=output_format, base_seed=seed, max_concurrency=max_concurrency,
    )

    notes: list[str] = []
    passed = True
    if not result.final.url.startswith("https://"):
        passed, _ = False, notes.append(f"expected a B2 https:// final URL, got {result.final.url}")
    if not result.manifest.verify():
        passed, _ = False, notes.append("final manifest.verify() returned False")
    return SmokeOutcome(passed=passed, mode="real", result=result, notes=notes)


# --------------------------------------------------------------------------
# Reporting + CLI
# --------------------------------------------------------------------------


def _report(outcome: SmokeOutcome, config: RunnerConfig) -> None:
    bar = "=" * 64
    print(bar)
    label = f"B2: {config.b2_bucket}" if outcome.mode == "real" else "no sink (file://)"
    print(f"Genblaze runner smoke — {outcome.mode.upper()} ({label})")
    print(f"Alias: {config.alias_base_url}")
    print(bar)

    result = outcome.result
    if result is not None:
        print(f"chunks: {len(result.chunks)}")
        for c in result.chunks:
            v = c.verdict or {}
            problems = ",".join(v.get("problems", [])) or "-"
            extra = []
            if c.attempts > 1:
                extra.append(f"re-rolled x{c.attempts - 1}")
            if c.trim_applied:
                extra.append("trimmed")
            tag = f"  ({'; '.join(extra)})" if extra else ""
            print(f"  #{c.position}  attempts={c.attempts}  score={v.get('score', '-')}  "
                  f"problems=[{problems}]{tag}")
            print(f"       {c.audio.url}")
        print(f"final: {result.final.url}")
        print(f"final manifest: {result.final_manifest_hash}  verify={result.manifest.verify()}")
        print(f"re-rolls: {result.reroll_count}")

    for note in outcome.notes:
        print(f"  ! {note}")
    print(f"RESULT: {'PASS' if outcome.passed else 'FAIL'}")
    print(bar)


def _env_summary() -> None:
    # ALIAS_* are the current names; BESPOKEN_* are still honored as a fallback.
    alias_keys = [("ALIAS_BASE_URL", "BESPOKEN_BASE_URL"), ("ALIAS_INTERNAL_SECRET", "BESPOKEN_INTERNAL_SECRET")]
    b2_keys = ["B2_BUCKET", "B2_KEY_ID", "B2_APP_KEY", "B2_REGION"]
    parts = [f"{new}={'set' if (os.getenv(new) or os.getenv(old)) else 'unset'}" for new, old in alias_keys]
    parts += [f"{k}={'set' if os.getenv(k) else 'unset'}" for k in b2_keys]
    print("env:", ", ".join(parts))


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Genblaze runner end-to-end smoke test.")
    parser.add_argument("--offline", action="store_true", help="force the offline self-test")
    parser.add_argument("--simulate-reroll", action="store_true", help="offline: script one re-roll")
    parser.add_argument("--text", default=DEFAULT_TEXT)
    parser.add_argument("--voice", default="default")
    parser.add_argument("--output-format", default="mp3_44100_128")
    parser.add_argument("--seed", type=int, default=None)
    parser.add_argument("--max-concurrency", type=int, default=1)
    args = parser.parse_args(argv)

    config = RunnerConfig.from_env()
    _env_summary()

    use_real = (not args.offline) and bool(config.b2_bucket) and bool(config.alias_internal_secret)
    if not use_real and not args.offline:
        print("note: B2/Alias env not fully set — running the OFFLINE self-test.\n")

    try:
        if use_real:
            outcome = run_real(config, text=args.text, voice=args.voice,
                               output_format=args.output_format, seed=args.seed,
                               max_concurrency=args.max_concurrency)
        else:
            outcome = run_offline(text=args.text, voice=args.voice,
                                  output_format=args.output_format, seed=args.seed,
                                  max_concurrency=args.max_concurrency,
                                  simulate_reroll=args.simulate_reroll)
    except Exception:  # noqa: BLE001
        traceback.print_exc()
        print("RESULT: FAIL (exception)")
        return 1

    _report(outcome, config)
    return 0 if outcome.passed else 1


if __name__ == "__main__":
    sys.exit(main())
