<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Approved final receipt — {{ $project->title }}</title>
<style>
  * { box-sizing: border-box; }
  body { margin: 0; font: 15px/1.55 ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, sans-serif; color: #18181b; background: #fff; }
  main { max-width: 880px; margin: 0 auto; padding: 2.5rem 1.5rem 4rem; }
  h1 { font-size: 1.5rem; margin: 0 0 .25rem; }
  .sub { color: #52525b; margin: 0 0 2rem; }
  .seal { border: 1px solid #a7f3d0; background: #ecfdf5; border-radius: .9rem; padding: 1.25rem 1.4rem; margin-bottom: 1.75rem; }
  .seal .ok { color: #047857; font-weight: 700; font-size: 1.05rem; }
  .seal dl { display: grid; grid-template-columns: max-content 1fr; gap: .35rem 1rem; margin: .9rem 0 0; }
  .seal dt { color: #047857; }
  .seal dd { margin: 0; }
  .hash { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; word-break: break-all; }
  .verify { margin-top: 1.1rem; padding-top: 1rem; border-top: 1px solid #a7f3d0; }
  .verify p { color: #047857; margin: .5rem 0 0; font-size: .9rem; }
  .verify a { color: #047857; font-weight: 600; word-break: break-all; }
  h2 { font-size: 1.05rem; margin: 2rem 0 .75rem; }
  /* Fixed layout + wrapping so long cells (the SHA and the QA summary) stay inside
     their columns instead of blowing the table past the page width. */
  table { width: 100%; border-collapse: collapse; font-size: .85rem; table-layout: fixed; }
  th, td { text-align: left; vertical-align: top; padding: .55rem .6rem; border-bottom: 1px solid #e4e4e7; overflow-wrap: anywhere; }
  th { color: #71717a; font-weight: 600; border-bottom: 2px solid #d4d4d8; }
  td.num { color: #52525b; }
  .chash { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: .72rem; color: #71717a; word-break: break-all; }
  .muted { color: #71717a; font-size: .82rem; }
  footer { margin-top: 2.5rem; color: #a1a1aa; font-size: .8rem; }
  @media print { .drop, .result { display: none !important; } }
</style>
</head>
<body>
<main>
  <h1>Approved final receipt</h1>
  <p class="sub">{{ $project->title }}</p>

  <div class="seal">
    <div class="ok">✓ Approved as the final</div>
    <dl>
      <dt>Approved by</dt><dd>{{ $project->sealApprover() ?? '—' }}</dd>
      <dt>Approved on</dt><dd>{{ optional($project->sealed_at)->toDayDateTimeString() ?? '—' }}</dd>
      <dt>File</dt><dd>{{ $finalName }} @if($project->final_bytes)· {{ number_format($project->final_bytes) }} bytes @endif @if($project->mime_type)· {{ $project->mime_type }}@endif</dd>
      <dt>Voice</dt><dd>{{ $manifest['project']['voice'] ?? '—' }}</dd>
      <dt>SHA-256</dt><dd class="hash">{{ $project->final_sha256 }}</dd>
    </dl>

    <div class="verify">
      <p>To confirm <strong>{{ $finalName }}</strong> is the untouched approved final, open
        <a href="{{ route('verify', ['sha' => $project->final_sha256]) }}">{{ route('verify') }}</a>
        and upload the file. Alias hashes it on the server and matches it against this sealed approval.</p>
    </div>
  </div>

  @include('partials.seal-provenance', ['chunks' => $chunks, 'finalName' => $finalName])

  <footer>
    Generated by Alias TTS. The machine-readable version of this receipt is in <code>manifest.json</code>.
    Verify a copy at <code>{{ route('verify') }}</code> — the server re-hashes it and matches it against
    the sealed approval.
  </footer>
</main>
</body>
</html>
