<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Sealed final receipt — {{ $project->title }}</title>
<style>
  * { box-sizing: border-box; }
  body { margin: 0; font: 15px/1.55 ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, sans-serif; color: #18181b; background: #fff; }
  main { max-width: 880px; margin: 0 auto; padding: 2.5rem 1.5rem 4rem; }
  h1 { font-size: 1.5rem; margin: 0 0 .25rem; }
  .sub { color: #52525b; margin: 0 0 2rem; }
  .seal { border: 1px solid #a7f3d0; background: #ecfdf5; border-radius: .9rem; padding: 1.25rem 1.4rem; margin-bottom: 1.75rem; }
  .seal .ok { color: #047857; font-weight: 700; font-size: 1.05rem; }
  .seal dl { display: grid; grid-template-columns: max-content 1fr; gap: .35rem 1rem; margin: .9rem 0 0; }
  .seal dt { color: #047857; }
  .seal dd { margin: 0; }
  .hash { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; word-break: break-all; }
  .verify { margin-top: 1.1rem; padding-top: 1rem; border-top: 1px solid #a7f3d0; }
  .verify a { display: inline-block; background: #059669; color: #fff; text-decoration: none; padding: .55rem 1rem; border-radius: .6rem; font-weight: 600; }
  .verify p { color: #047857; margin: .6rem 0 0; font-size: .9rem; }
  h2 { font-size: 1.05rem; margin: 2rem 0 .75rem; }
  table { width: 100%; border-collapse: collapse; font-size: .85rem; }
  th, td { text-align: left; vertical-align: top; padding: .55rem .6rem; border-bottom: 1px solid #e4e4e7; }
  th { color: #71717a; font-weight: 600; border-bottom: 2px solid #d4d4d8; }
  td.num { white-space: nowrap; color: #52525b; }
  .script { min-width: 16rem; }
  .chash { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: .72rem; color: #71717a; word-break: break-all; }
  .muted { color: #71717a; font-size: .82rem; }
  footer { margin-top: 2.5rem; color: #a1a1aa; font-size: .8rem; }
  @media print { .verify a { border: 1px solid #059669; } }
</style>
</head>
<body>
<main>
  <h1>Sealed final receipt</h1>
  <p class="sub">{{ $project->title }}</p>

  <div class="seal">
    <div class="ok">✓ Sealed as the approved final</div>
    <dl>
      <dt>Approved by</dt><dd>{{ $project->sealApprover() ?? '—' }}</dd>
      <dt>Sealed</dt><dd>{{ optional($project->sealed_at)->toDayDateTimeString() ?? '—' }}</dd>
      <dt>File</dt><dd>{{ $finalName }} @if($project->final_bytes)· {{ number_format($project->final_bytes) }} bytes @endif @if($project->mime_type)· {{ $project->mime_type }}@endif</dd>
      <dt>Voice</dt><dd>{{ $manifest['project']['voice'] ?? '—' }}</dd>
      <dt>SHA-256</dt><dd class="hash">{{ $project->final_sha256 }}</dd>
    </dl>

    <div class="verify">
      <a href="./verify.html#expect={{ $project->final_sha256 }}">Verify this file →</a>
      <p>Open <strong>verify.html</strong> (next to this receipt) and drag <strong>{{ $finalName }}</strong> onto it.
         It re-computes the fingerprint <em>on your device</em> — nothing is uploaded — and tells you
         whether the file is the untouched approved final. Works fully offline.</p>
    </div>
  </div>

  <h2>How it was made — {{ count($chunks) }} chunk{{ count($chunks) === 1 ? '' : 's' }}</h2>
  <table>
    <thead>
      <tr>
        <th>#</th>
        <th class="script">Script</th>
        <th>Voice</th>
        <th>Seed</th>
        <th>Source</th>
        <th>Takes</th>
        <th>QA</th>
        <th>Source audio SHA-256<br><span class="muted">(pre-trim / pre-stitch)</span></th>
      </tr>
    </thead>
    <tbody>
      @foreach($chunks as $row)
        <tr>
          <td class="num">{{ $row['position'] + 1 }}</td>
          <td class="script">{{ $row['text'] }}</td>
          <td class="num">
            {{ $row['voice'] ?? '—' }}
            @if($row['voice_inherited'])<br><span class="muted">project default</span>@endif
          </td>
          <td class="num">{{ $row['seed'] ?? '—' }}</td>
          <td class="num">{{ $row['source'] ?? '—' }}</td>
          <td class="num">{{ $row['attempts'] }}</td>
          <td class="num">
            @if($row['asr_score'] !== null){{ $row['asr_score'] }}@else—@endif
            @if($row['asr_summary'])<br><span class="muted">{{ $row['asr_summary'] }}</span>@endif
          </td>
          <td class="chash">{{ $row['source_audio_sha256'] ?? '—' }}</td>
        </tr>
      @endforeach
    </tbody>
  </table>

  <p class="muted" style="margin-top:1rem">
    The <strong>SHA-256</strong> above is the only fingerprint that verifies <strong>{{ $finalName }}</strong>
    byte-for-byte. The per-chunk hashes cover each chunk's source take <em>before</em> trimming, stitching,
    and re-encoding, so they document the inputs but won't reconstruct the final file.
  </p>

  <footer>
    Generated by Bespoken TTS. The machine-readable version of this receipt is in <code>manifest.json</code>.
  </footer>
</main>
</body>
</html>
